name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6']
    steps:
    - name: "Checkout code"
      uses: actions/checkout@v2

    - name: "Set up Python"
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: "Install Poetry"
      # The newer `install-poetry.py` is bugged: https://github.com/python-poetry/poetry/issues/3870
      run: >
        curl --silent --show-error https://raw.githubusercontent.com/python-poetry/poetry/7360b09e4ba3c01e1d5dc6eaaf34cb3ff57bc16e/get-poetry.py | python - --no-modify-path
      env:
        POETRY_VERSION: 1.1.6

    - name: "Install test dependencies"
      run: |
        ~/.poetry/bin/poetry install --no-root
        pip install -e .
      env:
        POETRY_VIRTUALENVS_CREATE: 0

    - name: Install gettext
      run: sudo apt-get install gettext
    - name: Check flake8
      run: flake8 .
    - name: Check isort
      run: isort --check --diff .
    - name: Check black
      run: black --check --diff .
    # - name: Run tests
      # run: py.test -ra -vvv shuup_mirage_field_tests --cov shuup_mirage_field
